# Generated by Django 3.2.6 on 2022-09-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customerlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='browsing_as_ghost',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='password2',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='confirm password'),
        ),
        migrations.DeleteModel(
            name='CustomerLocation',
        ),
    ]
