# Generated by Django 3.2.6 on 2022-09-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='custom_username',
            new_name='user_name',
        ),
    ]
