# Generated by Django 3.2.6 on 2022-09-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_custom_username_useraccount_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
