# Generated by Django 3.2.6 on 2022-09-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220915_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafestaffinformation',
            old_name='shift_hour',
            new_name='shift_end_hour',
        ),
        migrations.AddField(
            model_name='cafestaffinformation',
            name='shift_start_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
