# Generated by Django 3.2.6 on 2022-09-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_useraccount_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFcmDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('web', 'web'), ('ios', 'ios'), ('android', 'android')], default='android', max_length=25)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_fcm_devices', to='accounts.customerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StaffFcmDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('web', 'web'), ('ios', 'ios'), ('android', 'android')], default='android', max_length=25)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('hotel_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_fcm_devices', to='accounts.cafestaffinformation')),
            ],
        ),
        migrations.CreateModel(
            name='FcmNotificationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.stafffcmdevice')),
            ],
        ),
        migrations.CreateModel(
            name='FcmNotificationCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customerfcmdevice')),
            ],
        ),
    ]
