# Generated by Django 3.2.6 on 2022-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customerfcmdevice_fcmnotificationcustomer_fcmnotificationstaff_stafffcmdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(default='2022-10-10 12:00:00', max_length=35, unique=True),
            preserve_default=False,
        ),
    ]
