# Generated by Django 3.2.6 on 2022-10-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20221002_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(default='2022-09-10', max_length=35, unique=True),
            preserve_default=False,
        ),
    ]
