# Generated by Django 3.2.6 on 2022-10-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20221002_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='total_point',
            field=models.FloatField(default=0.0),
        ),
    ]
