# Generated by Django 3.2.6 on 2022-10-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customerinfo_total_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafestaffinformation',
            name='is_superadmin',
            field=models.BooleanField(default=True),
        ),
    ]
