# Generated by Django 3.2.6 on 2022-10-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_cafestaffinformation_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafestaffinformation',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
