# Generated by Django 3.2.6 on 2022-10-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_cafestaffinformation_is_superadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafffcmdevice',
            old_name='hotel_staff',
            new_name='cafe_staff',
        ),
    ]
