# Generated by Django 3.2.6 on 2022-09-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.FileField(default='', upload_to='food'),
            preserve_default=False,
        ),
    ]
