# Generated by Django 3.2.6 on 2022-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='food'),
        ),
    ]
