# Generated by Django 3.2.6 on 2022-09-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='cloud_cafe_information',
        ),
    ]
