# Generated by Django 3.2.6 on 2022-09-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customerfcmdevice_fcmnotificationcustomer_fcmnotificationstaff_stafffcmdevice'),
        ('cafe', '0004_remove_cafe_cloud_cafe_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wish_lists', to='accounts.customerinfo')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wish_lists', to='cafe.food')),
            ],
        ),
    ]
