# Generated by Django 3.2.6 on 2022-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-09-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-09-10 10:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='status',
            field=models.CharField(choices=[('ORDER_PLACED', 'User Confirmed'), ('PREPARING', 'Preparing'), ('PICKED', 'Picked'), ('ON_THE_WAY', 'On the Way'), ('DELIVERED', 'Delivered'), ('INVOICE', 'Invoice'), ('CANCELLED', 'Cancelled')], default='USER_CONFIRMED', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='status',
            field=models.CharField(choices=[('ORDER_PLACED', 'User Confirmed'), ('PREPARING', 'Preparing'), ('PICKED', 'Picked'), ('ON_THE_WAY', 'On the Way'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='ORDER_PLACED', max_length=120),
        ),
    ]
